### ISSUE TITLE
Error during `def-to-gds`

### ISSUE THREAD

**Issue by kareefardi** [efabless/utilities#4]
Got the following error when running this command:
```
utilities def-to-gds --pdk-root $HOME/work/pdk --pdk sky130A --extra-lef ./example.lef --output out user_project_wrapper.def
```

```
DEF read, Line 1312 (Error): Cell user_proj_example is not defined.  Maybe you have not read the corresponding LEF file?
```
Here are `example.lef` and `user_project_wrapper.def`:
[design.tar.gz](https://github.com/efabless/utilities/files/12586880/design.tar.gz)

**Comment by marwaneltoukhy** [comment]
fixed here 0c7e8283220e2f9f0874c77b67a48160d9b65c62
